sudo: required
services:
  - docker

before_install:
  - docker build -t lwalton99/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lwalton99/docker-react npm run test -- --coverage
 
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react2"
  env: "docker-react2-env"
  bucket_name: "elasticbeanstalk-us-east-2-569121403348"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  